blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/yourusername/InventoryX/blob/main/README.md
    about: Check out the project documentation
  - name: 💬 Discussions
    url: https://github.com/yourusername/InventoryX/discussions
    about: Ask questions and discuss ideas with the community
